name: flutter_learn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.4
  import_lint: ^0.1.6


flutter:
  uses-material-design: true
  assets:
    - assets/landscape.jpg